//
//  CompanyCatalog.swift
//  subscriptionManager
//
//  Auto-generated from companies.json for offline catalog fallback.
//

import Foundation

enum CompanyCatalog {
    static let all: [Company] = [
        Company(id: "netflix", name: "Netflix", aliases: ["Netflix Inc"], domains: ["netflix.com"], category: .streaming, brandColor: "#E50914", logoAssetName: "NetflixLogo"),
        Company(id: "spotify", name: "Spotify", aliases: ["Spotify AB", "Spotify Premium"], domains: ["spotify.com"], category: .music, brandColor: "#1DB954", logoAssetName: "SpotifyLogo"),
        Company(id: "apple_music", name: "Apple Music", aliases: ["Apple Music Subscription", "iTunes Music"], domains: ["apple.com", "music.apple.com"], category: .music, brandColor: "#FC3C44", logoAssetName: "AppleMusicLogo"),
        Company(id: "apple_tv", name: "Apple TV+", aliases: ["Apple TV Plus", "AppleTV"], domains: ["tv.apple.com"], category: .streaming, brandColor: "#000000", logoAssetName: "AppleTVLogo"),
        Company(id: "apple_one", name: "Apple One", aliases: ["Apple One Bundle"], domains: ["apple.com"], category: .other, brandColor: "#000000", logoAssetName: "AppleOneLogo"),
        Company(id: "apple_icloud", name: "iCloud+", aliases: ["iCloud", "iCloud Storage", "Apple iCloud"], domains: ["icloud.com"], category: .cloud, brandColor: "#3693F3", logoAssetName: "iCloudLogo"),
        Company(id: "disney_plus", name: "Disney+", aliases: ["Disney Plus", "DisneyPlus", "Disney+ Subscription"], domains: ["disneyplus.com", "disney.com"], category: .streaming, brandColor: "#113CCF", logoAssetName: "DisneyPlusLogo"),
        Company(id: "hbo_max", name: "Max", aliases: ["HBO Max", "HBO", "Warner Bros Max"], domains: ["max.com", "hbomax.com"], category: .streaming, brandColor: "#002BE7", logoAssetName: "MaxLogo"),
        Company(id: "hulu", name: "Hulu", aliases: ["Hulu LLC", "Hulu + Live TV"], domains: ["hulu.com"], category: .streaming, brandColor: "#1CE783", logoAssetName: "HuluLogo"),
        Company(id: "amazon_prime", name: "Amazon Prime", aliases: ["Prime Video", "Amazon Prime Video", "Prime Membership"], domains: ["amazon.com", "primevideo.com"], category: .streaming, brandColor: "#00A8E1", logoAssetName: "AmazonPrimeLogo"),
        Company(id: "youtube_premium", name: "YouTube Premium", aliases: ["YouTube Music", "YouTube TV", "YouTube Red"], domains: ["youtube.com", "music.youtube.com"], category: .streaming, brandColor: "#FF0000", logoAssetName: "YouTubeLogo 1"),
        Company(id: "paramount_plus", name: "Paramount+", aliases: ["Paramount Plus", "CBS All Access"], domains: ["paramountplus.com"], category: .streaming, brandColor: "#0064FF", logoAssetName: "ParamountPlusLogo"),
        Company(id: "peacock", name: "Peacock", aliases: ["Peacock TV", "NBCUniversal Peacock"], domains: ["peacocktv.com"], category: .streaming, brandColor: "#000000", logoAssetName: "PeacockLogo"),
        Company(id: "crunchyroll", name: "Crunchyroll", aliases: ["Crunchyroll Premium"], domains: ["crunchyroll.com"], category: .streaming, brandColor: "#F47521", logoAssetName: "CrunchyrollLogo"),
        Company(id: "tidal", name: "TIDAL", aliases: ["Tidal Music", "Tidal HiFi"], domains: ["tidal.com"], category: .music, brandColor: "#000000", logoAssetName: "TidalLogo"),
        Company(id: "deezer", name: "Deezer", aliases: ["Deezer Premium"], domains: ["deezer.com"], category: .music, brandColor: "#FEAA2D", logoAssetName: "DeezerLogo"),
        Company(id: "soundcloud", name: "SoundCloud", aliases: ["SoundCloud Go", "SoundCloud Go+"], domains: ["soundcloud.com"], category: .music, brandColor: "#FF5500", logoAssetName: "SoundCloudLogo"),
        Company(id: "pandora", name: "Pandora", aliases: ["Pandora Music", "Pandora Premium", "Pandora Plus"], domains: ["pandora.com"], category: .music, brandColor: "#3668FF", logoAssetName: "PandoraLogo"),
        Company(id: "adobe_cc", name: "Adobe Creative Cloud", aliases: ["Adobe CC", "Adobe Subscription", "Adobe All Apps", "Adobe Photoshop", "Adobe Illustrator", "Adobe Premiere"], domains: ["adobe.com", "creativecloud.adobe.com"], category: .productivity, brandColor: "#FF0000", logoAssetName: "AdobeLogo"),
        Company(id: "microsoft_365", name: "Microsoft 365", aliases: ["Office 365", "Microsoft Office", "M365"], domains: ["microsoft.com", "office.com"], category: .productivity, brandColor: "#0078D4", logoAssetName: "Microsoft365Logo"),
        Company(id: "google_one", name: "Google One", aliases: ["Google Storage", "Google Drive Storage"], domains: ["one.google.com", "google.com"], category: .cloud, brandColor: "#4285F4", logoAssetName: "GoogleOneLogo"),
        Company(id: "google_workspace", name: "Google Workspace", aliases: ["G Suite", "Google Apps"], domains: ["workspace.google.com"], category: .productivity, brandColor: "#4285F4", logoAssetName: "GoogleWorkspaceLogo"),
        Company(id: "dropbox", name: "Dropbox", aliases: ["Dropbox Plus", "Dropbox Professional"], domains: ["dropbox.com"], category: .cloud, brandColor: "#0061FF", logoAssetName: "DropboxLogo"),
        Company(id: "notion", name: "Notion", aliases: ["Notion Plus", "Notion Team"], domains: ["notion.so", "notion.com"], category: .productivity, brandColor: "#000000", logoAssetName: "NotionLogo"),
        Company(id: "slack", name: "Slack", aliases: ["Slack Pro", "Slack Business"], domains: ["slack.com"], category: .productivity, brandColor: "#4A154B", logoAssetName: "SlackLogo"),
        Company(id: "figma", name: "Figma", aliases: ["Figma Professional", "Figma Organization"], domains: ["figma.com"], category: .productivity, brandColor: "#F24E1E", logoAssetName: "FigmaLogo"),
        Company(id: "canva", name: "Canva", aliases: ["Canva Pro", "Canva for Teams"], domains: ["canva.com"], category: .productivity, brandColor: "#00C4CC", logoAssetName: "CanvaLogo"),
        Company(id: "grammarly", name: "Grammarly", aliases: ["Grammarly Premium", "Grammarly Business"], domains: ["grammarly.com"], category: .productivity, brandColor: "#15C39A", logoAssetName: "GrammarlyLogo"),
        Company(id: "1password", name: "1Password", aliases: ["1Password Families", "1Password Teams"], domains: ["1password.com"], category: .vpn, brandColor: "#0094F5", logoAssetName: "1PasswordLogo"),
        Company(id: "lastpass", name: "LastPass", aliases: ["LastPass Premium", "LastPass Families"], domains: ["lastpass.com"], category: .vpn, brandColor: "#D32D27", logoAssetName: "LastPassLogo"),
        Company(id: "bitwarden", name: "Bitwarden", aliases: ["Bitwarden Premium"], domains: ["bitwarden.com"], category: .vpn, brandColor: "#175DDC", logoAssetName: "BitwardenLogo"),
        Company(id: "nordvpn", name: "NordVPN", aliases: ["Nord VPN", "Nord Security"], domains: ["nordvpn.com"], category: .vpn, brandColor: "#4687FF", logoAssetName: "NordVPNLogo"),
        Company(id: "expressvpn", name: "ExpressVPN", aliases: ["Express VPN"], domains: ["expressvpn.com"], category: .vpn, brandColor: "#DA3940", logoAssetName: "ExpressVPNLogo"),
        Company(id: "surfshark", name: "Surfshark", aliases: ["Surfshark VPN"], domains: ["surfshark.com"], category: .vpn, brandColor: "#178DE9", logoAssetName: "SurfsharkLogo"),
        Company(id: "chatgpt", name: "ChatGPT", aliases: ["ChatGPT Plus", "OpenAI ChatGPT", "GPT Plus"], domains: ["openai.com", "chat.openai.com"], category: .ai, brandColor: "#10A37F", logoAssetName: "OpenAILogo"),
        Company(id: "claude", name: "Claude", aliases: ["Claude Pro", "Anthropic Claude", "Claude AI"], domains: ["anthropic.com", "claude.ai"], category: .ai, brandColor: "#D97757", logoAssetName: "ClaudeLogo"),
        Company(id: "midjourney", name: "Midjourney", aliases: ["MidJourney AI"], domains: ["midjourney.com"], category: .ai, brandColor: "#000000", logoAssetName: "MidjourneyLogo"),
        Company(id: "github", name: "GitHub", aliases: ["GitHub Pro", "GitHub Copilot", "GitHub Team"], domains: ["github.com"], category: .productivity, brandColor: "#181717", logoAssetName: "GitHubLogo"),
        Company(id: "gitlab", name: "GitLab", aliases: ["GitLab Premium", "GitLab Ultimate"], domains: ["gitlab.com"], category: .productivity, brandColor: "#FC6D26", logoAssetName: "GitLabLogo"),
        Company(id: "xbox_game_pass", name: "Xbox Game Pass", aliases: ["Game Pass", "Xbox Game Pass Ultimate", "PC Game Pass"], domains: ["xbox.com", "microsoft.com"], category: .gaming, brandColor: "#107C10", logoAssetName: "XboxLogo"),
        Company(id: "playstation_plus", name: "PlayStation Plus", aliases: ["PS Plus", "PSN Plus", "PlayStation Now"], domains: ["playstation.com"], category: .gaming, brandColor: "#003791", logoAssetName: "PlayStationLogo"),
        Company(id: "nintendo_online", name: "Nintendo Switch Online", aliases: ["Nintendo Online", "NSO"], domains: ["nintendo.com"], category: .gaming, brandColor: "#E60012", logoAssetName: "NintendoLogo"),
        Company(id: "ea_play", name: "EA Play", aliases: ["EA Access", "EA Play Pro"], domains: ["ea.com"], category: .gaming, brandColor: "#000000", logoAssetName: "EALogo"),
        Company(id: "twitch", name: "Twitch", aliases: ["Twitch Turbo", "Twitch Prime"], domains: ["twitch.tv"], category: .gaming, brandColor: "#9146FF", logoAssetName: "TwitchLogo"),
        Company(id: "discord", name: "Discord", aliases: ["Discord Nitro", "Nitro"], domains: ["discord.com", "discordapp.com"], category: .social, brandColor: "#5865F2", logoAssetName: "DiscordLogo"),
        Company(id: "linkedin", name: "LinkedIn", aliases: ["LinkedIn Premium", "LinkedIn Learning", "LinkedIn Sales Navigator"], domains: ["linkedin.com"], category: .social, brandColor: "#0A66C2", logoAssetName: "LinkedInLogo"),
        Company(id: "twitter", name: "X", aliases: ["Twitter", "X Premium", "Twitter Blue"], domains: ["x.com", "twitter.com"], category: .social, brandColor: "#000000", logoAssetName: "XLogo"),
        Company(id: "strava", name: "Strava", aliases: ["Strava Premium", "Strava Summit"], domains: ["strava.com"], category: .fitness, brandColor: "#FC4C02", logoAssetName: "StravaLogo"),
        Company(id: "peloton", name: "Peloton", aliases: ["Peloton Digital", "Peloton App"], domains: ["onepeloton.com", "peloton.com"], category: .fitness, brandColor: "#000000", logoAssetName: "PelotonLogo"),
        Company(id: "fitbit", name: "Fitbit", aliases: ["Fitbit Premium"], domains: ["fitbit.com"], category: .fitness, brandColor: "#00B0B9", logoAssetName: "FitbitLogo"),
        Company(id: "myfitnesspal", name: "MyFitnessPal", aliases: ["MyFitnessPal Premium", "MFP"], domains: ["myfitnesspal.com"], category: .fitness, brandColor: "#0069D1", logoAssetName: "MyFitnessPalLogo"),
        Company(id: "headspace", name: "Headspace", aliases: ["Headspace Plus"], domains: ["headspace.com"], category: .fitness, brandColor: "#F47D31", logoAssetName: "HeadspaceLogo"),
        Company(id: "calm", name: "Calm", aliases: ["Calm Premium", "Calm App"], domains: ["calm.com"], category: .fitness, brandColor: "#7FDBFF", logoAssetName: "CalmLogo"),
        Company(id: "nytimes", name: "The New York Times", aliases: ["NYTimes", "NY Times", "New York Times Digital"], domains: ["nytimes.com"], category: .news, brandColor: "#000000", logoAssetName: "NYTimesLogo"),
        Company(id: "wsj", name: "The Wall Street Journal", aliases: ["WSJ", "Wall Street Journal"], domains: ["wsj.com"], category: .news, brandColor: "#0080C3", logoAssetName: "WSJLogo"),
        Company(id: "washington_post", name: "The Washington Post", aliases: ["Washington Post", "WaPo"], domains: ["washingtonpost.com"], category: .news, brandColor: "#000000", logoAssetName: "WashingtonPostLogo"),
        Company(id: "economist", name: "The Economist", aliases: ["Economist Digital"], domains: ["economist.com"], category: .news, brandColor: "#E3120B", logoAssetName: "EconomistLogo"),
        Company(id: "medium", name: "Medium", aliases: ["Medium Membership"], domains: ["medium.com"], category: .news, brandColor: "#000000", logoAssetName: "MediumLogo"),
        Company(id: "substack", name: "Substack", aliases: ["Substack Subscription"], domains: ["substack.com"], category: .news, brandColor: "#FF6719", logoAssetName: "SubstackLogo"),
        Company(id: "audible", name: "Audible", aliases: ["Audible Premium", "Amazon Audible"], domains: ["audible.com"], category: .education, brandColor: "#F8991D", logoAssetName: "AudibleLogo"),
        Company(id: "kindle_unlimited", name: "Kindle Unlimited", aliases: ["Kindle", "Amazon Kindle"], domains: ["amazon.com"], category: .education, brandColor: "#FF9900", logoAssetName: "KindleLogo"),
        Company(id: "masterclass", name: "MasterClass", aliases: ["Master Class"], domains: ["masterclass.com"], category: .education, brandColor: "#000000", logoAssetName: "MasterClassLogo"),
        Company(id: "skillshare", name: "Skillshare", aliases: ["Skillshare Premium"], domains: ["skillshare.com"], category: .education, brandColor: "#00FF84", logoAssetName: "SkillshareLogo"),
        Company(id: "coursera", name: "Coursera", aliases: ["Coursera Plus"], domains: ["coursera.org"], category: .education, brandColor: "#0056D2", logoAssetName: "CourseraLogo"),
        Company(id: "duolingo", name: "Duolingo", aliases: ["Duolingo Plus", "Duolingo Super"], domains: ["duolingo.com"], category: .education, brandColor: "#58CC02", logoAssetName: "DuolingoLogo"),
        Company(id: "doordash", name: "DoorDash", aliases: ["DashPass", "DoorDash DashPass"], domains: ["doordash.com"], category: .food, brandColor: "#FF3008", logoAssetName: "DoorDashLogo"),
        Company(id: "uber_eats", name: "Uber Eats", aliases: ["Uber One", "Uber Eats Pass"], domains: ["ubereats.com", "uber.com"], category: .food, brandColor: "#06C167", logoAssetName: "UberEatsLogo"),
        Company(id: "grubhub", name: "Grubhub", aliases: ["Grubhub+"], domains: ["grubhub.com"], category: .food, brandColor: "#F63440", logoAssetName: "GrubhubLogo"),
        Company(id: "instacart", name: "Instacart", aliases: ["Instacart+", "Instacart Express"], domains: ["instacart.com"], category: .food, brandColor: "#43B02A", logoAssetName: "InstacartLogo"),
        Company(id: "walmart_plus", name: "Walmart+", aliases: ["Walmart Plus"], domains: ["walmart.com"], category: .shopping, brandColor: "#0071DC", logoAssetName: "WalmartLogo"),
        Company(id: "costco", name: "Costco", aliases: ["Costco Membership", "Costco Executive"], domains: ["costco.com"], category: .shopping, brandColor: "#E31837", logoAssetName: "CostcoLogo"),
        Company(id: "amazon_prime_membership", name: "Amazon Prime", aliases: ["Prime Membership", "Amazon Prime Subscription"], domains: ["amazon.com"], category: .shopping, brandColor: "#FF9900", logoAssetName: "AmazonLogo"),
        Company(id: "zoom", name: "Zoom", aliases: ["Zoom Pro", "Zoom Business"], domains: ["zoom.us", "zoom.com"], category: .productivity, brandColor: "#2D8CFF", logoAssetName: "ZoomLogo"),
        Company(id: "evernote", name: "Evernote", aliases: ["Evernote Premium", "Evernote Personal"], domains: ["evernote.com"], category: .productivity, brandColor: "#00A82D", logoAssetName: "EvernoteLogo"),
        Company(id: "todoist", name: "Todoist", aliases: ["Todoist Pro", "Todoist Business"], domains: ["todoist.com"], category: .productivity, brandColor: "#E44332", logoAssetName: "TodoistLogo"),
        Company(id: "asana", name: "Asana", aliases: ["Asana Premium", "Asana Business"], domains: ["asana.com"], category: .productivity, brandColor: "#F06A6A", logoAssetName: "AsanaLogo"),
        Company(id: "trello", name: "Trello", aliases: ["Trello Premium", "Trello Standard"], domains: ["trello.com"], category: .productivity, brandColor: "#0052CC", logoAssetName: "TrelloLogo"),
        Company(id: "linear", name: "Linear", aliases: ["Linear App"], domains: ["linear.app"], category: .productivity, brandColor: "#5E6AD2", logoAssetName: "LinearLogo"),
        Company(id: "gmail", name: "Gmail", aliases: ["Google Mail"], domains: ["gmail.com", "mail.google.com"], category: .productivity, brandColor: "#EA4335", logoAssetName: "GmailLogo 1"),
        Company(id: "proton_mail", name: "Proton Mail", aliases: ["ProtonMail", "Proton Unlimited"], domains: ["proton.me", "protonmail.com"], category: .utilities, brandColor: "#6D4AFF", logoAssetName: "ProtonLogo"),
        Company(id: "dashlane", name: "Dashlane", aliases: ["Dashlane Premium", "Dashlane Business"], domains: ["dashlane.com"], category: .vpn, brandColor: "#0E6B52", logoAssetName: "DashlaneLogo"),
        Company(id: "setapp", name: "Setapp", aliases: ["Setapp Subscription"], domains: ["setapp.com"], category: .productivity, brandColor: "#7B68EE", logoAssetName: "SetappLogo"),
        Company(id: "bear", name: "Bear", aliases: ["Bear Pro", "Bear Notes"], domains: ["bear.app"], category: .productivity, brandColor: "#DD4C4F", logoAssetName: "BearLogo"),
        Company(id: "craft", name: "Craft", aliases: ["Craft Pro", "Craft Docs"], domains: ["craft.do"], category: .productivity, brandColor: "#000000", logoAssetName: "CraftLogo"),
        Company(id: "arc", name: "Arc", aliases: ["Arc Browser", "The Browser Company"], domains: ["arc.net", "thebrowser.company"], category: .utilities, brandColor: "#000000", logoAssetName: "ArcLogo"),
        Company(id: "superhuman", name: "Superhuman", aliases: ["Superhuman Mail"], domains: ["superhuman.com"], category: .productivity, brandColor: "#4169E1", logoAssetName: "SuperhumanLogo"),
        Company(id: "raycast", name: "Raycast", aliases: ["Raycast Pro"], domains: ["raycast.com"], category: .productivity, brandColor: "#FF6363", logoAssetName: "RaycastLogo"),
        Company(id: "cleanmymac", name: "CleanMyMac", aliases: ["CleanMyMac X", "MacPaw CleanMyMac"], domains: ["macpaw.com", "cleanmymac.com"], category: .utilities, brandColor: "#26ABE3", logoAssetName: "CleanMyMacLogo"),
        Company(id: "parallels", name: "Parallels", aliases: ["Parallels Desktop"], domains: ["parallels.com"], category: .utilities, brandColor: "#FF3333", logoAssetName: "ParallelsLogo"),
        Company(id: "sketch", name: "Sketch", aliases: ["Sketch App"], domains: ["sketch.com"], category: .productivity, brandColor: "#F7B500", logoAssetName: "SketchLogo"),
        Company(id: "affinity", name: "Affinity", aliases: ["Affinity Designer", "Affinity Photo", "Serif Affinity"], domains: ["affinity.serif.com"], category: .productivity, brandColor: "#4ECFF2", logoAssetName: "AffinityLogo"),
        Company(id: "procreate", name: "Procreate", aliases: ["Procreate Dreams"], domains: ["procreate.com"], category: .productivity, brandColor: "#000000", logoAssetName: "ProcreateLogo"),
        Company(id: "espn_plus", name: "ESPN+", aliases: ["ESPN Plus", "ESPN Streaming"], domains: ["espn.com", "plus.espn.com"], category: .streaming, brandColor: "#FF0033", logoAssetName: "ESPN_"),
        Company(id: "discovery_plus", name: "Discovery+", aliases: ["Discovery Plus"], domains: ["discoveryplus.com"], category: .streaming, brandColor: "#0033FF", logoAssetName: "Discovery_"),
        Company(id: "amc_plus", name: "AMC+", aliases: ["AMC Plus", "AMC Streaming"], domains: ["amcplus.com", "amc.com"], category: .streaming, brandColor: "#000000", logoAssetName: "AMC_"),
        Company(id: "showtime", name: "Showtime", aliases: ["Showtime Streaming", "SHO"], domains: ["showtime.com", "sho.com"], category: .streaming, brandColor: "#FF0000", logoAssetName: "Showtime"),
        Company(id: "starz", name: "Starz", aliases: ["Starz Streaming"], domains: ["starz.com"], category: .streaming, brandColor: "#000000", logoAssetName: "Starz"),
        Company(id: "mubi", name: "Mubi", aliases: ["Mubi Streaming"], domains: ["mubi.com"], category: .streaming, brandColor: "#001489", logoAssetName: "Mubi"),
        Company(id: "criterion_channel", name: "Criterion Channel", aliases: ["Criterion Collection"], domains: ["criterionchannel.com"], category: .streaming, brandColor: "#000000", logoAssetName: "Criterion_Channel"),
        Company(id: "britbox", name: "BritBox", aliases: ["Brit Box"], domains: ["britbox.com"], category: .streaming, brandColor: "#E30613", logoAssetName: "BritBox"),
        Company(id: "shudder", name: "Shudder", aliases: ["Shudder Horror"], domains: ["shudder.com"], category: .streaming, brandColor: "#000000", logoAssetName: "Shudder"),
        Company(id: "dazn", name: "DAZN", aliases: ["DAZN Sports"], domains: ["dazn.com"], category: .streaming, brandColor: "#F7D200", logoAssetName: "DAZN"),
        Company(id: "apple_fitness", name: "Apple Fitness+", aliases: ["Apple Fitness Plus", "Fitness+"], domains: ["apple.com", "fitness.apple.com"], category: .fitness, brandColor: "#FA243C", logoAssetName: "AppleMusicLogo"),
        Company(id: "amazon_music", name: "Amazon Music", aliases: ["Amazon Music Unlimited", "Prime Music"], domains: ["music.amazon.com", "amazon.com"], category: .music, brandColor: "#25D1DA", logoAssetName: "Amazon_Music"),
        Company(id: "plex", name: "Plex", aliases: ["Plex Pass"], domains: ["plex.tv"], category: .streaming, brandColor: "#EBAF00", logoAssetName: "Plex"),
        Company(id: "monday", name: "Monday.com", aliases: ["Monday", "Monday Work OS"], domains: ["monday.com"], category: .productivity, brandColor: "#FF3D57", logoAssetName: "Monday_com"),
        Company(id: "clickup", name: "ClickUp", aliases: ["ClickUp Productivity"], domains: ["clickup.com"], category: .productivity, brandColor: "#7B68EE", logoAssetName: "ClickUp"),
        Company(id: "airtable", name: "Airtable", aliases: ["Airtable Pro"], domains: ["airtable.com"], category: .productivity, brandColor: "#18BFFF", logoAssetName: "Airtable"),
        Company(id: "coda", name: "Coda", aliases: ["Coda Docs"], domains: ["coda.io"], category: .productivity, brandColor: "#F46A54", logoAssetName: "Coda"),
        Company(id: "miro", name: "Miro", aliases: ["Miro Board", "Miro Whiteboard"], domains: ["miro.com"], category: .productivity, brandColor: "#FFD02F", logoAssetName: "Miro"),
        Company(id: "loom", name: "Loom", aliases: ["Loom Video"], domains: ["loom.com"], category: .productivity, brandColor: "#625DF5", logoAssetName: "Loom"),
        Company(id: "calendly", name: "Calendly", aliases: ["Calendly Pro"], domains: ["calendly.com"], category: .productivity, brandColor: "#006BFF", logoAssetName: "Calendly"),
        Company(id: "zapier", name: "Zapier", aliases: ["Zapier Automation"], domains: ["zapier.com"], category: .productivity, brandColor: "#FF4A00", logoAssetName: "Zapier"),
        Company(id: "webflow", name: "Webflow", aliases: ["Webflow Design"], domains: ["webflow.com"], category: .productivity, brandColor: "#4353FF", logoAssetName: "Webflow"),
        Company(id: "vercel", name: "Vercel", aliases: ["Vercel Pro"], domains: ["vercel.com"], category: .productivity, brandColor: "#000000", logoAssetName: "Vercel"),
        Company(id: "netlify", name: "Netlify", aliases: ["Netlify Pro"], domains: ["netlify.com"], category: .productivity, brandColor: "#00C7B7", logoAssetName: "Netlify"),
        Company(id: "backblaze", name: "Backblaze", aliases: ["Backblaze Backup"], domains: ["backblaze.com"], category: .cloud, brandColor: "#E21E29", logoAssetName: "Backblaze"),
        Company(id: "box", name: "Box", aliases: ["Box Cloud"], domains: ["box.com"], category: .cloud, brandColor: "#0061D5", logoAssetName: "Box"),
        Company(id: "pcloud", name: "pCloud", aliases: ["pCloud Storage"], domains: ["pcloud.com"], category: .cloud, brandColor: "#00BFFF", logoAssetName: "pCloud"),
        Company(id: "keeper", name: "Keeper", aliases: ["Keeper Security", "Keeper Password"], domains: ["keepersecurity.com"], category: .vpn, brandColor: "#0070C0", logoAssetName: "Keeper"),
        Company(id: "pia", name: "Private Internet Access", aliases: ["PIA", "PIA VPN"], domains: ["privateinternetaccess.com"], category: .vpn, brandColor: "#4BB543", logoAssetName: "Private_Internet_Access"),
        Company(id: "cyberghost", name: "CyberGhost", aliases: ["CyberGhost VPN"], domains: ["cyberghostvpn.com"], category: .vpn, brandColor: "#FFCC00", logoAssetName: "CyberGhost"),
        Company(id: "mullvad", name: "Mullvad", aliases: ["Mullvad VPN"], domains: ["mullvad.net"], category: .vpn, brandColor: "#294D73", logoAssetName: "Mullvad"),
        Company(id: "perplexity", name: "Perplexity", aliases: ["Perplexity AI", "Perplexity Pro"], domains: ["perplexity.ai"], category: .ai, brandColor: "#20808D", logoAssetName: "Perplexity"),
        Company(id: "jasper", name: "Jasper", aliases: ["Jasper AI"], domains: ["jasper.ai"], category: .ai, brandColor: "#7C3AED", logoAssetName: "Jasper"),
        Company(id: "runway", name: "Runway", aliases: ["Runway ML", "Runway AI"], domains: ["runwayml.com"], category: .ai, brandColor: "#000000", logoAssetName: "Runway"),
        Company(id: "elevenlabs", name: "ElevenLabs", aliases: ["Eleven Labs", "ElevenLabs AI"], domains: ["elevenlabs.io"], category: .ai, brandColor: "#000000", logoAssetName: "ElevenLabs"),
        Company(id: "descript", name: "Descript", aliases: ["Descript Video"], domains: ["descript.com"], category: .ai, brandColor: "#00D1A1", logoAssetName: "Descript"),
        Company(id: "otter", name: "Otter.ai", aliases: ["Otter", "Otter Transcription"], domains: ["otter.ai"], category: .ai, brandColor: "#3B82F6", logoAssetName: "Otter_ai"),
        Company(id: "udemy", name: "Udemy", aliases: ["Udemy Business"], domains: ["udemy.com"], category: .education, brandColor: "#A435F0", logoAssetName: "Udemy"),
        Company(id: "brilliant", name: "Brilliant", aliases: ["Brilliant Premium"], domains: ["brilliant.org"], category: .education, brandColor: "#000000", logoAssetName: "Brilliant"),
        Company(id: "blinkist", name: "Blinkist", aliases: ["Blinkist Premium"], domains: ["blinkist.com"], category: .education, brandColor: "#0B9C5B", logoAssetName: "Blinkist"),
        Company(id: "scribd", name: "Scribd", aliases: ["Scribd Premium"], domains: ["scribd.com"], category: .education, brandColor: "#1A7BBA", logoAssetName: "Scribd"),
        Company(id: "bloomberg", name: "Bloomberg", aliases: ["Bloomberg News", "Bloomberg Digital"], domains: ["bloomberg.com"], category: .news, brandColor: "#000000", logoAssetName: "Bloomberg"),
        Company(id: "financial_times", name: "Financial Times", aliases: ["FT", "FT Digital"], domains: ["ft.com"], category: .news, brandColor: "#FFF1E5", logoAssetName: "Financial_Times"),
        Company(id: "the_atlantic", name: "The Atlantic", aliases: ["Atlantic Magazine"], domains: ["theatlantic.com"], category: .news, brandColor: "#000000", logoAssetName: "The_Atlantic"),
        Company(id: "new_yorker", name: "The New Yorker", aliases: ["New Yorker Magazine"], domains: ["newyorker.com"], category: .news, brandColor: "#000000", logoAssetName: "The_New_Yorker"),
        Company(id: "wired", name: "Wired", aliases: ["Wired Magazine"], domains: ["wired.com"], category: .news, brandColor: "#000000", logoAssetName: "Wired"),
        Company(id: "nike_training", name: "Nike Training Club", aliases: ["NTC", "Nike Training"], domains: ["nike.com"], category: .fitness, brandColor: "#000000", logoAssetName: "Nike_Training_Club"),
        Company(id: "whoop", name: "WHOOP", aliases: ["Whoop Fitness"], domains: ["whoop.com"], category: .fitness, brandColor: "#44D7B6", logoAssetName: "WHOOP"),
        Company(id: "oura", name: "Oura", aliases: ["Oura Ring", "Oura Membership"], domains: ["ouraring.com"], category: .fitness, brandColor: "#000000", logoAssetName: "Oura"),
        Company(id: "classpass", name: "ClassPass", aliases: ["Class Pass"], domains: ["classpass.com"], category: .fitness, brandColor: "#0047FF", logoAssetName: "ClassPass"),
        Company(id: "noom", name: "Noom", aliases: ["Noom Weight"], domains: ["noom.com"], category: .fitness, brandColor: "#FF6B00", logoAssetName: "Noom"),
        Company(id: "betterhelp", name: "BetterHelp", aliases: ["Better Help"], domains: ["betterhelp.com"], category: .fitness, brandColor: "#00A693", logoAssetName: "BetterHelp"),
        Company(id: "talkspace", name: "Talkspace", aliases: ["Talk Space"], domains: ["talkspace.com"], category: .fitness, brandColor: "#00B4A2", logoAssetName: "Talkspace"),
        Company(id: "reddit_premium", name: "Reddit Premium", aliases: ["Reddit Gold"], domains: ["reddit.com"], category: .social, brandColor: "#FF4500", logoAssetName: "Reddit_Premium"),
        Company(id: "snapchat_plus", name: "Snapchat+", aliases: ["Snapchat Plus"], domains: ["snapchat.com"], category: .social, brandColor: "#FFFC00", logoAssetName: "Snapchat_"),
        Company(id: "patreon", name: "Patreon", aliases: ["Patreon Membership"], domains: ["patreon.com"], category: .social, brandColor: "#FF424D", logoAssetName: "Patreon"),
        Company(id: "ynab", name: "YNAB", aliases: ["You Need A Budget"], domains: ["ynab.com"], category: .other, brandColor: "#85C0EA", logoAssetName: "YNAB"),
        Company(id: "copilot_money", name: "Copilot", aliases: ["Copilot Money", "Copilot Finance"], domains: ["copilot.money"], category: .other, brandColor: "#000000", logoAssetName: "Copilot"),
        Company(id: "monarch", name: "Monarch Money", aliases: ["Monarch", "Monarch Finance"], domains: ["monarchmoney.com"], category: .other, brandColor: "#5046E5", logoAssetName: "Monarch_Money"),
        Company(id: "robinhood_gold", name: "Robinhood Gold", aliases: ["Robinhood"], domains: ["robinhood.com"], category: .other, brandColor: "#00C805", logoAssetName: "Robinhood_Gold"),
        Company(id: "geforce_now", name: "GeForce NOW", aliases: ["Nvidia GeForce Now", "GFN"], domains: ["nvidia.com"], category: .gaming, brandColor: "#76B900", logoAssetName: "GeForce_NOW"),
        Company(id: "ubisoft_plus", name: "Ubisoft+", aliases: ["Ubisoft Plus"], domains: ["ubisoft.com"], category: .gaming, brandColor: "#000000", logoAssetName: "Ubisoft_"),
        Company(id: "steam", name: "Steam", aliases: ["Valve Steam"], domains: ["steampowered.com"], category: .gaming, brandColor: "#1B2838", logoAssetName: "Steam"),
        Company(id: "hello_fresh", name: "HelloFresh", aliases: ["Hello Fresh"], domains: ["hellofresh.com"], category: .food, brandColor: "#94C11E", logoAssetName: "HelloFresh"),
        Company(id: "blue_apron", name: "Blue Apron", aliases: ["BlueApron"], domains: ["blueapron.com"], category: .food, brandColor: "#0066CC", logoAssetName: "Blue_Apron"),
        Company(id: "shipt", name: "Shipt", aliases: ["Shipt Delivery"], domains: ["shipt.com"], category: .food, brandColor: "#17B471", logoAssetName: "Shipt"),
        Company(id: "squarespace", name: "Squarespace", aliases: ["Squarespace Websites"], domains: ["squarespace.com"], category: .productivity, brandColor: "#000000", logoAssetName: "Squarespace"),
        Company(id: "wix", name: "Wix", aliases: ["Wix Premium"], domains: ["wix.com"], category: .productivity, brandColor: "#000000", logoAssetName: "Wix"),
        Company(id: "shopify", name: "Shopify", aliases: ["Shopify Basic", "Shopify Plus"], domains: ["shopify.com"], category: .productivity, brandColor: "#96BF48", logoAssetName: "Shopify"),
        Company(id: "mailchimp", name: "Mailchimp", aliases: ["Mail Chimp"], domains: ["mailchimp.com"], category: .productivity, brandColor: "#FFE01B", logoAssetName: "Mailchimp"),
        Company(id: "hubspot", name: "HubSpot", aliases: ["Hub Spot"], domains: ["hubspot.com"], category: .productivity, brandColor: "#FF7A59", logoAssetName: "HubSpot"),
        Company(id: "stripe", name: "Stripe", aliases: ["Stripe Payments"], domains: ["stripe.com"], category: .other, brandColor: "#635BFF", logoAssetName: "Stripe"),
        Company(id: "twilio", name: "Twilio", aliases: ["Twilio Communications"], domains: ["twilio.com"], category: .productivity, brandColor: "#F22F46", logoAssetName: "Twilio"),
        Company(id: "datadog", name: "Datadog", aliases: ["Data Dog"], domains: ["datadoghq.com"], category: .productivity, brandColor: "#632CA6", logoAssetName: "Datadog"),
        Company(id: "sentry", name: "Sentry", aliases: ["Sentry.io"], domains: ["sentry.io"], category: .productivity, brandColor: "#362D59", logoAssetName: "Sentry"),
        Company(id: "new_relic", name: "New Relic", aliases: ["NewRelic"], domains: ["newrelic.com"], category: .productivity, brandColor: "#00AC69", logoAssetName: "New_Relic"),
        Company(id: "atlassian", name: "Atlassian", aliases: ["Atlassian Cloud", "Jira", "Confluence"], domains: ["atlassian.com"], category: .productivity, brandColor: "#0052CC", logoAssetName: "Atlassian"),
        Company(id: "jira", name: "Jira", aliases: ["Jira Software", "Jira Cloud"], domains: ["atlassian.com"], category: .productivity, brandColor: "#0052CC", logoAssetName: "Jira"),
        Company(id: "confluence", name: "Confluence", aliases: ["Atlassian Confluence"], domains: ["atlassian.com"], category: .productivity, brandColor: "#172B4D", logoAssetName: "Confluence"),
        Company(id: "bitbucket", name: "Bitbucket", aliases: ["Atlassian Bitbucket"], domains: ["bitbucket.org"], category: .productivity, brandColor: "#0052CC", logoAssetName: "Bitbucket"),
        Company(id: "postman", name: "Postman", aliases: ["Postman API"], domains: ["postman.com"], category: .productivity, brandColor: "#FF6C37", logoAssetName: "Postman"),
        Company(id: "intercom", name: "Intercom", aliases: ["Intercom Support"], domains: ["intercom.com"], category: .productivity, brandColor: "#1F8DED", logoAssetName: "Intercom"),
        Company(id: "zendesk", name: "Zendesk", aliases: ["Zendesk Support"], domains: ["zendesk.com"], category: .productivity, brandColor: "#03363D", logoAssetName: "Zendesk"),
        Company(id: "freshdesk", name: "Freshdesk", aliases: ["Freshworks"], domains: ["freshdesk.com"], category: .productivity, brandColor: "#00A651", logoAssetName: "Freshdesk"),
        Company(id: "typeform", name: "Typeform", aliases: ["Typeform Surveys"], domains: ["typeform.com"], category: .productivity, brandColor: "#262627", logoAssetName: "Typeform"),
        Company(id: "surveymonkey", name: "SurveyMonkey", aliases: ["Survey Monkey"], domains: ["surveymonkey.com"], category: .productivity, brandColor: "#00BF6F", logoAssetName: "SurveyMonkey"),
        Company(id: "docusign", name: "DocuSign", aliases: ["Docu Sign"], domains: ["docusign.com"], category: .productivity, brandColor: "#FFD02E", logoAssetName: "DocuSign"),
        Company(id: "dropbox_sign", name: "Dropbox Sign", aliases: ["HelloSign"], domains: ["hellosign.com"], category: .productivity, brandColor: "#0061FF", logoAssetName: "Dropbox_Sign"),
        Company(id: "1password_business", name: "1Password Business", aliases: ["1Password Teams"], domains: ["1password.com"], category: .vpn, brandColor: "#0094F5", logoAssetName: "1Password_Business"),
        Company(id: "okta", name: "Okta", aliases: ["Okta Identity"], domains: ["okta.com"], category: .productivity, brandColor: "#007DC1", logoAssetName: "Okta"),
        Company(id: "auth0", name: "Auth0", aliases: ["Auth Zero"], domains: ["auth0.com"], category: .productivity, brandColor: "#EB5424", logoAssetName: "Auth0"),
    ]
}
